server:
   port: 8081

spring:
  application:
    name: rocketmq-producer
  datasource:
    hikari:
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521/helowin
      username: test
      password: test
      driver-class-name: oracle.jdbc.driver.OracleDriver
      max-idle: 10
      max-wait: 1000
      min-idle: 5
      initial-size: 5

app:
  id: chihuo
apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true

logging:
  level:
    com.chihuo.sharding: debug

####################################Producer###################################
#是否开启自动配置
rocketmq:
  producer:
    isOnOff: on
#发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    groupName: ${spring.application.name}
#mq的nameserver地址
    namesrvAddr: 127.0.0.1:9876
#消息最大长度 默认 1024 * 4 (4M)
    maxMessageSize: 4096
#发送消息超时时间，默认 3000
    sendMsgTimeOut: 3000
#发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2